# Generated by Django 6.0.1 on 2026-01-31 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("police_station", models.CharField(max_length=255)),
                ("investigating_officer_name", models.CharField(max_length=255)),
                ("investigating_officer_id", models.CharField(max_length=100)),
                ("crime_number", models.CharField(max_length=100)),
                ("crime_year", models.IntegerField()),
                ("date_of_fir", models.DateField()),
                ("date_of_seizure", models.DateField()),
                ("act_and_law", models.CharField(max_length=255)),
                ("section_of_law", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DISPOSED", "Disposed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "belonging_to",
                    models.CharField(
                        choices=[
                            ("ACCUSED", "Accused"),
                            ("COMPLAINANT", "Complainant"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nature_of_property", models.CharField(max_length=255)),
                ("quantity_units", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        help_text="Rack / Room / Locker ID", max_length=255
                    ),
                ),
                ("description", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_photos/"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="inventory.case",
                    ),
                ),
            ],
        ),
    ]
